[versions]
kotlin="2.1.20-Beta2"
compose_reload_kotlin = "2.1.20-firework.34"
kotlin_coroutines="1.9.0"
kotlin_serialization="1.7.3"
compose_hot_reload = "1.0.0-dev-39"
compose="1.7.3"
ktlint_plugin="12.1.2"
adam="0.5.10"
junit="5.11.4"
koin="4.0.2"
system_theme_detector="3.9.1"
ktor = "3.1.0"
lucide = "1.1.0"
coil = "3.0.4"

[libraries]
adam = { module = "com.malinskiy.adam:adam", version.ref = "adam" }
kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin_coroutines" }
kotlin_serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin_serialization" }
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
jSystemThemeDetectorVer = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "system_theme_detector" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
lucide = { module = "com.composables:icons-lucide", version.ref = "lucide" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
hot-reload-core = { module = "org.jetbrains.compose:hot-reload-core", version.ref = "compose_hot_reload" }
hot-reload-analysis = { module = "org.jetbrains.compose:hot-reload-analysis", version.ref = "compose_hot_reload" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "compose_reload_kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "compose_reload_kotlin" }
compose-hot-reload = { id = "org.jetbrains.compose-hot-reload", version.ref = "compose_hot_reload" }

compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "compose_reload_kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint_plugin" }
