[versions]
kotlin="1.9.23"
kotlin_coroutines="1.8.0"
kotlin_serialization="1.7.3"
compose="1.7.1+build1894-release-1.7.1"
ktlint_plugin="12.1.1"
adam="0.5.8"
junit="5.11.3"
koin="4.0.0"
system_theme_detector="3.9.1"
ktor = "2.3.12"

[libraries]
adam = { module = "com.malinskiy.adam:adam", version.ref = "adam" }
kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin_coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin_coroutines" }
kotlin_serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin_serialization" }
junit5 = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
jSystemThemeDetectorVer = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "system_theme_detector" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint_plugin" }
